### ISSUE TITLE
Add `geography_mapper.csv` and `ecoinvent_complete_new.csv` on Databricks and update data flow

### ISSUE THREAD

**Issue by kalashsinghal** [2DegreesInvesting/tiltDataPipelines#101]
@ysherstyuk Please add two files `geography_mapper.csv` and `ecoinvent_complete_new.csv` on Databricks. These two files are shared via google drive link I shared on slack. These are input files for tiltIndicatorBefore. Thanks!

**Comment by ysherstyuk** [comment]
Hi @kalashsinghal,

Both files are onboarded to the storage. FYI I had to remove 'Product Information' column from the ecoinvent_complete_new, as it had some odd formatting that didn't allow to pass the data through the data pipeline. I think this column is not being used anywhere. Can you please test the files on your side? Thanks!

**Comment by kalashsinghal** [comment]
@ysherstyuk Yes you are right! The column 'Product Information' is not used anywhere in tiltIndicatorBefore. Hence, it can be deleted. Please close this issue if its done! :)
