### ISSUE TITLE
Generating toydata for tiltIndicatorBefore

### ISSUE THREAD

**Issue by ysherstyuk** [2DegreesInvesting/tiltDataPipelines#111]
Hi @kalashsinghal,

As discussed yesterday, we will be working on generating toydata, which will be included to the data pipelines so sample data can be generated from the latest data taken from the storage whenever there is a new release of the package.

We would need data requirements and specifications for both packages from your side and also please share any prior work on that (e.g., an approach on getting certain companies to be joined with products and not just random rows, details on the discussion with Anne on anonymizing data to share a snippet of input and output in GitHub).

Can you please include the above to this ticket so it's easier to trace. 

Thank you so much in advance!

**Comment by kalashsinghal** [comment]
UPDATE: I will work on creating toy datasets for tiltIndicatorAfter using https://github.com/2DegreesInvesting/tiltToyData/issues/14

**Comment by kalashsinghal** [comment]
Hi @SKruthoff,
May you please share the toydatasets for tiltIndicatorBefore here as well?

cc' @Tilmon
