### ISSUE TITLE
Resolve remaining data loading issues on Databricks for tiltIndictorBefore

### ISSUE THREAD

**Issue by kalashsinghal** [2DegreesInvesting/tiltDataPipelines#115]
Dear @ysherstyuk @SKruthoff 

I have resolved a lot of data loading issues for databricks by using this [PR](https://github.com/2DegreesInvesting/tiltIndicatorBefore/pull/85). However, there are some issues which can only be resolved in the data storage of cloud. Please resolve these remaining issues:

1. In file `tilt_isic_mapper_2023-07-20`, column `isic_4digit` is read as an integer/float column due to which values like `0111` are read as `111` in tiltIndictorBefore. Please change the type of this column to string so that all integers can be read with the leading zero.
2. In file `geography_mapper`, column `input_priority` is read as `string` type instead of `float`. This column only consists numbers and hence please change its type from string to float. 
3. In file `ecoinvent_complete_new`, I experienced that some string values are overflown to other columns. I saw this issue before as well in other datasets. I came across this issue by noticing values like "fuels" in `isic_4digit` column: 

![image](https://github.com/2DegreesInvesting/tiltDataPipelines/assets/125359076/329291fc-8f5e-4631-b1a9-96cae9e71419)

Please feel free to ask any questions if its unclear!

**Comment by Tilmon** [comment]
hi @kalashsinghal @SKruthoff @ysherstyuk just saw this bug now after a while. Has this been picked up / solved already?

**Comment by kalashsinghal** [comment]
@Tilmon I think they are resolved but @ysherstyuk @SKruthoff have to confirm to close this issue :)
