### ISSUE TITLE
Update column type in table `tilt_isic_mapper_2023-07-20` 

### ISSUE THREAD

**Issue by kalashsinghal** [2DegreesInvesting/tiltDataPipelines#62]
@ysherstyuk 

Column `isic_4digit` in table `tilt_isic_mapper_2023-07-20` has values of `int16` type which converts an integer 011 into 11. However, column type should be `string` and also please check if there are values like 011 in the column after you change the type to string. Thanks!

**Comment by ysherstyuk** [comment]
Hi @kalashsinghal 

Good point! Changed the data type to string and also tested, all works. Please check yourself as well

**Comment by kalashsinghal** [comment]
@ysherstyuk Looks good to me now! Thanks for resolving this issue
