### ISSUE TITLE
Column `country_id` in table `companies` has weird values

### ISSUE THREAD

**Issue by kalashsinghal** [2DegreesInvesting/tiltDataPipelines#64]
Dear @ysherstyuk 

Column `country_id` in table `companies` can only have these five values: 

1. 9aec35c79b4e91fefb2a310d33bd736a14c961d8
2. 23e591e8c36dda987970603ad0fdd031b7dff9f9
3. 1fe80e506149e4b49ca3560003edd2b8d57e6d9e
4. 51288d140528c2d5c0565891be70300a9b0e365f
5. 6ace185eedb813fe84c2eca7641f9fa0aa3bfdc3

However, I can see some weird values in this `country_id` column like `http://www.lightfab.de/index.php/home_en.html` and `http://www.tool-holder.com/index.php?id=2&l=1`. Please investigate from where these values come from! Thanks!

**Comment by ysherstyuk** [comment]
Hi @kalashsinghal!

This is the setup done by Mauro from the tiltData package, we just incorporated it in the data pipeline. There is also a mapping table countries, where there are county names and country ids. It is the normalisation way that Mauro used in the database that he created. Country id is generated from sha method, so for all values there is a similar format. Please let me know if you need more explanation.

**Comment by kalashsinghal** [comment]
Hi @ysherstyuk 
The `companies` dataset I have in my local system does not have any other value than the 5 values I mentioned. Due to which every row in the `companies` dataset has a valid country value after mapping with the `countries` table in my local system.  FYI: This `countries` table also has `country_id` column which is used to map countries for `companies` dataset. 

If those weird values will remain in the `county_id` column then there might be some rows in the final dataframe which don't have the info about which countries they belong to, which is not ideal. 

I can share the `companies` file I have in my system which don't have such values if you would like see.

**Comment by SKruthoff** [comment]
Hi, this is again a string formatting issue, where quote characters are included in the company information column. This is not aligning with the given schema of the file. I have made adaptations in the input files, so now the companies table should be in order. Additionally, I have also added a check to make sure that the country_id column only has the 5 possible values from the country table.

**Comment by kalashsinghal** [comment]
@SKruthoff Above issue is resolved, however I can see a new issue after you resolved this one. 
The `postcode` column in `companies` dataset has 156906 null values. `postcode` column should not have any null value, hence please investigate why this column has null values. Thanks!

**Comment by SKruthoff** [comment]
Again the formatting of the initial input file was in the way, but I see that there are no more empty values in the postcode column.

**Comment by kalashsinghal** [comment]
@SKruthoff Looks good to me now!
