### ISSUE TITLE
Null values are read as Non-null values with spark in table `categories`

### ISSUE THREAD

**Issue by kalashsinghal** [2DegreesInvesting/tiltDataPipelines#65]
Dear @ysherstyuk 

Column `subsector` in table `categories` have null values (NaN for pandas dataframe), however these null values are read as string values ("NA") with spark. Please change them back to null values. Thanks!

**Comment by ysherstyuk** [comment]
Hi @kalashsinghal,

This is fixed now! The table returns null values. Can you please test?

FYI we have implemented the functionality to change NA to null for all tables, however not all tables were regenerated to use this functionality. So in case you encounter the same issue again, please mention in which table, so we can regenerate it as well.

Thanks!

**Comment by kalashsinghal** [comment]
@ysherstyuk Tested
Looks good to me! Thanks :)
