### ISSUE TITLE
Add IndicatorBefore flow to as-is data model

### ISSUE THREAD

**Issue by bobresink** [2DegreesInvesting/tiltDataPipelines#70]
@kalashsinghal we need to add the data used in the IndicatorBefore code to the AS-IS tab of the below data model:

https://app.diagrams.net/#G1lx8d7Y-K93jZ0OGd1L3j0flsXxUipK2w

If this is added, the data model can be finished such that we can start constructing an efficient to-be data model.

I will set up a short call for this week such that we can finish it.

**Comment by kalashsinghal** [comment]
@bobresink I have added tiltIndicatorBefore data model in the AS-IS tab of the data model. Please let me know if you need a call for alignment
