### ISSUE TITLE
Create domain values table containing DQ checks

### ISSUE THREAD

**Issue by ysherstyuk** [2DegreesInvesting/tiltDataPipelines#79]
The domain table would contain a list of checks and possible values for specific columns, similar to dictionary in the backend, but for analysts to be able to run specific checks and analyze data quality

**Comment by bobresink** [comment]
@ysherstyuk and this one?

**Comment by ysherstyuk** [comment]
This was Merel's idea, so I assume we would still need it, and since Letizia is working on the data quality checks now, I would assign it to her:)
