### ISSUE TITLE
Review Tilman's script for testing mappers and include it in the standard procedure for data validation before running tiltIndicatorBefore

### ISSUE THREAD

**Issue by Tilmon** [2DegreesInvesting/tiltDataPipelines#99]
Dear @kalashsinghal , 

in the past, we often ran into issues with the indicator calculation due to wrongly specified sector mappers (manual analysts' input). To avoid that in the future, I created a script that uses all sector mappers as inputs, joins them as we do it in tiltIndicatorBefore and outputs the unique combinations of mapped sectors & co2 reduction targets. 

This makes it very easy to identify in which cases mapping worked and in which not. If mapping didn't work, it needs to be validated whether that is expected or not. If not, analysts need to revise the input data. 

I think if this script can be somehow integrated into the indicator pipeline in the sense that every time before one re-runs tiltIndicatorBefore, the mappers are tested with this script to avoid re-running the tiltIndicatorBefore over and over again. 

Therefore, I suggest you: 

- review the R project attached
- re-write code as needed and think with @maurolepore and @bobresink about how/where this test can be included

Pls let me know if you have any questions. I'll be gone from July 31, so best to make sure everything is clear before I'm gone so that you don't run into the same issues again when analysts update mappers in the next 3 months. 

Thanks!

cc' @maurolepore 

[script_mapper_testing.zip](https://github.com/2DegreesInvesting/tiltIndicator/files/12104897/script_mapper_testing.zip)

**Comment by AnneSchoenauer** [comment]
@bobresink I am unassigning the MT team from here as I think it lies with you. Please let us know if there are questions to this specific task! :)
